#![allow(unused_variables)]

use wasm_bindgen::prelude::*;

/// JS helper generated by build.rs (WGSL embedded, TypeScript stripped).
const JS_HELPER: &str = include_str!(concat!(env!("OUT_DIR"), "/helper.min.js"));

/// Evaluate JS code. In Node.js tests this is provided by test-webgpu-setup.mjs
/// as `globalThis.jsEval` (a saved reference to `eval` before the webgpu native
/// module corrupts the `globalThis` binding). In browser tests `globalThis.jsEval`
/// falls back to `eval` itself.
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_name = jsEval)]
    fn js_eval(code: &str) -> JsValue;
}

/// Check whether the current JS environment supports WebGPU.
/// In browsers: checks `navigator.gpu`. In Node.js (node-webgpu): checks `GPU` global.
fn has_webgpu() -> bool {
    let has_it = js_eval("(typeof navigator !== 'undefined' && !!navigator.gpu) || (typeof GPU !== 'undefined')");
    has_it.as_bool().unwrap_or(false)
}

/// Call the WebGPU extract function. Returns a `Vec<u8>` of RGB values.
pub async fn extract_palette_webgpu(
    pixels: &[u8],
    width: u32,
    height: u32,
    color_count: u8,
    quality: u8,
) -> Result<Vec<u8>, String> {
    if !has_webgpu() {
        return Err("WebGPU is not available in this environment".to_string());
    }

    let extract_fn = js_eval(JS_HELPER);

    // Build input object
    let input = js_sys::Object::new();
    let pixels_arr = js_sys::Uint8Array::from(pixels);
    js_sys::Reflect::set(&input, &JsValue::from_str("pixels"), &pixels_arr.into()).ok();
    js_sys::Reflect::set(
        &input,
        &JsValue::from_str("w"),
        &JsValue::from_f64(width as f64),
    )
    .ok();
    js_sys::Reflect::set(
        &input,
        &JsValue::from_str("h"),
        &JsValue::from_f64(height as f64),
    )
    .ok();
    js_sys::Reflect::set(
        &input,
        &JsValue::from_str("maxC"),
        &JsValue::from_f64(color_count as f64),
    )
    .ok();
    js_sys::Reflect::set(
        &input,
        &JsValue::from_str("quality"),
        &JsValue::from_f64(quality as f64),
    )
    .ok();

    // Call the function via Reflect.apply
    let call_args = js_sys::Array::new();
    call_args.push(&input.into());
    let fn_ref = extract_fn.unchecked_ref::<js_sys::Function>();
    let promise_val = js_sys::Reflect::apply(fn_ref, &JsValue::UNDEFINED, &call_args)
        .map_err(|e| format!("WebGPU call failed: {:?}", e))?;

    // Convert JsValue to Promise for JsFuture
    let promise = js_sys::Promise::from(promise_val);
    let result = wasm_bindgen_futures::JsFuture::from(promise)
        .await
        .map_err(|e| format!("WebGPU promise rejected: {:?}", e))?;

    let uint8 = js_sys::Uint8Array::from(result);
    let mut out = vec![0u8; uint8.length() as usize];
    uint8.copy_to(&mut out);
    Ok(out)
}
