FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:ondrej/php && \
    apt-get update && \
    apt-get install -y php8.1-dev libclang-dev && \
    rm -rf /var/lib/apt/lists/*
