FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y php8.2-cli libonig-dev libclang-dev wget && \
    wget -q https://www.php.net/distributions/php-8.2.0.tar.xz -O /tmp/php.tar.xz && \
    tar xf /tmp/php.tar.xz -C /tmp && \
    mkdir -p /usr/include/php && \
    cp -r /tmp/php-8.2.0/main/* /usr/include/php/ && \
    cp -r /tmp/php-8.2.0/Zend/* /usr/include/php/ && \
    cp -r /tmp/php-8.2.0/TSRM/* /usr/include/php/ && \
    cd /usr/include/php && \
    sed -e 's/#undef ZEND_SIGNALS/#define ZEND_SIGNALS 0/' \
        -e 's/#undef PHP_EXPORT_SYMBOLC/#define PHP_EXPORT_SYMBOL 1/' \
        -e 's/@ZEND_SIGNALS@/0/g' \
        -e 's/@PHP_EXPORT_SYMBOL@/1/g' \
        -e 's/@PHP_MAJOR_VERSION@/8/g' \
        -e 's/@PHP_MINOR_VERSION@/2/g' \
        -e 's/@PHP_RELEASE_VERSION@/0/g' \
        -e 's/@PHP_EXTRA_VERSION@//g' \
        -e 's/@PHP_VERSION@/8.2.0/g' \
        -e 's/@PHP_VERSION_ID@/80200/g' \
        -e 's/@PHP_BUILD_DIR@//g' \
        -e 's/@PHP_PREFIX@//g' \
        -e 's/@PHP_BINDIR@//g' \
        -e 's/@PHP_LIBDIR@//g' \
        -e 's/@PHP_MANDIR@//g' \
        -e 's/@PHP_SYSCONFDIR@//g' \
        -e 's/@PHP_LOCALSTATEDIR@//g' \
        -e 's/@PHP_CONFIG_FILE_PATH@//g' \
        -e 's/@PHP_CONFIG_FILE_SCAN_DIR@//g' \
        -e 's/@PHP_EXTENSION_DIR@//g' \
        -e 's/@EXTRA_LIBXML@//g' \
        -e 's/@LIBXML@//g' \
        -e 's/@EXTRA_LIBS@//g' \
        -e 's/@PHP_RPATH@//g' \
        -e 's/@PHP_LT_SYS_LIBDPATH@//g' \
        -e 's/@PHP_ZEND_DEBUG@/0/g' \
        -e 's/@ZEND_DEBUG@/0/g' \
        -e 's/@PHP_ZEND_DLEXPORT@//g' \
        -e 's/@PHP_DLEXPORT@//g' \
        -e 's/@PHP_DTRACE_HEADER@//g' \
        -e 's/@PHP_DTRACE_ENABLED@/0/g' \
        -e 's/@PHP_DTRACE_USDT_ENABLED@/0/g' \
        -e 's/@PHP_DEBUG@/0/g' \
        -e 's/@PHP_HAVE_BUNDLED_ZLIB@/0/g' \
        php_config.h.in > php_config.h && \
    rm -rf /tmp/php-8.2.0 /tmp/php.tar.xz
