/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Extract the dominant color from raw RGBA pixel data.
 *
 * @param pixels - Raw RGBA pixel buffer (4 bytes per pixel)
 * @param width - Image width in pixels
 * @param height - Image height in pixels
 * @param quality - Sampling quality, higher is faster but less accurate (default: 10)
 * @returns [R, G, B] color tuple
 */
export declare function getColor(pixels: Uint8Array, width: number, height: number, quality?: number | undefined | null): Array<number>

/**
 * Extract a palette of dominant colors from raw RGBA pixel data.
 *
 * @param pixels - Raw RGBA pixel buffer (4 bytes per pixel)
 * @param width - Image width in pixels
 * @param height - Image height in pixels
 * @param colorCount - Number of colors to extract (default: 10)
 * @param quality - Sampling quality, higher is faster but less accurate (default: 10)
 * @returns Array of [R, G, B] color tuples
 */
export declare function getPalette(pixels: Uint8Array, width: number, height: number, colorCount?: number | undefined | null, quality?: number | undefined | null): Array<Array<number>>
