#!/usr/bin/env bash
# Setup PHP cross-compilation environment for aarch64-unknown-linux-gnu
# Uses ext-php-rs PHP_CONFIG ergonomics — no manual sed on php_config.h.in
set -euo pipefail

PHP_VER="${PHP_CROSS_VERSION:-8.2.0}"
PHP_SOURCE_URL="https://www.php.net/distributions/php-${PHP_VER}.tar.xz"
PREFIX="${PHP_CROSS_PREFIX:-/usr}"
INCLUDE_DIR="${PHP_CROSS_INCLUDE_DIR:-${PREFIX}/include/php}"
PHP_CONFIG_PATH="${PHP_CROSS_CONFIG_PATH:-${PREFIX}/bin/php-config-aarch64}"

# 1. Install cross-compile toolchain + PHP source headers
sudo apt-get update
sudo apt-get install -y gcc-aarch64-linux-gnu libclang-dev wget

# 2. Download & extract PHP source (for headers only)
wget --tries=5 -q "${PHP_SOURCE_URL}" -O /tmp/php.tar.xz
tar xf /tmp/php.tar.xz -C /tmp

# 3. Install headers preserving source tree layout
#    zend_portability.h uses relative includes:
#      #include "../TSRM/TSRM.h" (from Zend/)
#      #include "main/php_config.h" (from TSRM/)
#    Copying the dirs as-is keeps these relative paths working
sudo cp -r "/tmp/php-${PHP_VER}/main" "${PREFIX}/include/"
sudo cp -r "/tmp/php-${PHP_VER}/Zend" "${PREFIX}/include/"
sudo cp -r "/tmp/php-${PHP_VER}/TSRM" "${PREFIX}/include/"
# php.h does #include "zend.h" (bare), so Zend headers must also be flat
sudo cp -r "/tmp/php-${PHP_VER}/Zend/"* "${PREFIX}/include/"
# zend_virtual_cwd.h does #include "TSRM.h" (bare), so copy that flat too
sudo cp "/tmp/php-${PHP_VER}/TSRM/TSRM.h" "${PREFIX}/include/"
# zend_virtual_cwd.h uses DIR without including dirent.h — prepend it
sudo sed -i '1i#include <dirent.h>' "${PREFIX}/include/zend_virtual_cwd.h"
# ext-php-rs needs ext/standard/info.h for PHP_INFO_TYPE_TABLE macros
sudo mkdir -p "${PREFIX}/include/ext/standard"
sudo cp "/tmp/php-${PHP_VER}/ext/standard/info.h" "${PREFIX}/include/ext/standard/"

# 4. Patch zend_alloc.h — prepend ZEND_MM_ALIGNMENT define at the top
#    The include chain (zend.h -> zend_alloc.h) does not include zend_config.h
#    before zend_alloc.h checks ZEND_MM_ALIGNMENT, so the #error fires even
#    though zend_config.h defines it. Prepend the define to bypass the check.
sudo sed -i '1i#define ZEND_MM_ALIGNMENT 8' "${PREFIX}/include/zend_alloc.h"

# 5. Generate php_config.h from the .in template
sudo sh -c "cd ${PREFIX}/include/main && \
  sed -e 's/#undef ZEND_SIGNALS/#define ZEND_SIGNALS 0/' \
      -e 's/#undef PHP_EXPORT_SYMBOL/#define PHP_EXPORT_SYMBOL 1/' \
      -e 's/@ZEND_SIGNALS@/0/g' \
      -e 's/@PHP_EXPORT_SYMBOL@/1/g' \
      -e \"s/@PHP_MAJOR_VERSION@/$(echo ${PHP_VER} | cut -d. -f1)/g\" \
      -e \"s/@PHP_MINOR_VERSION@/$(echo ${PHP_VER} | cut -d. -f2)/g\" \
      -e \"s/@PHP_RELEASE_VERSION@/$(echo ${PHP_VER} | cut -d. -f3)/g\" \
      -e 's/@PHP_EXTRA_VERSION@//g' \
      -e \"s/@PHP_VERSION@/${PHP_VER}/g\" \
      -e \"s/@PHP_VERSION_ID@/$(echo ${PHP_VER} | tr -d .)/g\" \
      -e 's|@[^@]*@||g' \
      php_config.h.in > php_config.h && \
  echo '#define SIZEOF_SIZE_T 8' >> php_config.h"

# 6. Create zend_config.h (generated by ./configure, not in source tarball)
#    ext-php-rs needs it for zend_portability.h macros
sudo tee "${PREFIX}/include/Zend/zend_config.h" "${PREFIX}/include/zend_config.h" > /dev/null << 'ZENDCONFIG'
#ifndef ZEND_CONFIG_H
#define ZEND_CONFIG_H
#define ZEND_SIGNALS 0
#define ZEND_DEBUG 0
#define ZEND_ENABLE_STATIC_TSRMLS_CACHE 0
#define ZEND_MULTIBYTE 1
#define ZEND_MAX_EXECUTABLE_BYTES (256*1024*1024)
#define ZEND_DONT_UNLOAD_MODULES 0
#define ZEND_DONT_SERIALIZE_LITERALS 0
#define ZEND_DONT_OVERLOAD_FILE_FUNCS 0
#define ZEND_DEFAULT_STACK_SIZE 0
#define ZEND_DEFAULT_MAX_EXECUTION_TIME 30
#define ZEND_MM_CACHE_SIZE 1024
#define ZEND_MM_ALIGNMENT 8
#endif /* ZEND_CONFIG_H */
ZENDCONFIG

# 7. Clean up source tarball
rm -rf "/tmp/php-${PHP_VER}" /tmp/php.tar.xz

# 8. Write a php-config stub for ext-php-rs PHP_CONFIG ergonomics
#    Uses printf '%s' instead of echo to avoid trailing newline in output
#    (ext-php-rs parses --includes output; trailing newline corrupts the path)
sudo tee "${PHP_CONFIG_PATH}" > /dev/null << 'PHPCONFIG'
#!/bin/sh
prefix=/usr
exec_prefix=/usr
bindir=/usr/bin
includedir=/usr/include
extension_dir=/usr/lib/php/20170718
phpbinary=/usr/bin/php
version="8.2.0"
phplibdir=/usr/lib

for arg in "$@"; do
  case $arg in
    --prefix) printf '%s' "$prefix" ;;
    --exec-prefix) printf '%s' "$exec_prefix" ;;
    --version) printf '%s' "$version" ;;
    --includes) printf '%s' "-I${includedir}/main -I${includedir}" ;;
    --extension-dir) printf '%s' "$extension_dir" ;;
    --php-binary) printf '%s' "$phpbinary" ;;
    --libdir) printf '%s' "$phplibdir" ;;
    --bindir) printf '%s' "$bindir" ;;
    --ini-path) printf '%s' "/etc/php/8.2/cli" ;;
    --ini-dir) printf '%s' "/etc/php/8.2/cli" ;;
    --ldflags) printf '%s' "-L${phplibdir}" ;;
    --libs) printf '%s' "" ;;
    --cflags) printf '%s' "" ;;
    *) printf '%s' "php-config ${version}" ;;
  esac
done
PHPCONFIG
sudo chmod +x "${PHP_CONFIG_PATH}"

echo "PHP cross-compilation environment ready (${PHP_VER})"
echo "  PHP_CONFIG: ${PHP_CONFIG_PATH}"
echo "  Includes:   ${INCLUDE_DIR}"
