use wasm_bindgen::prelude::*;

/// JS helper generated by build.rs (WGSL embedded, TypeScript stripped).
const JS_HELPER: &str = include_str!(concat!(env!("OUT_DIR"), "/helper.min.js"));

/// Bind to `globalThis.eval` so JS code runs in the global scope.
#[wasm_bindgen(js_namespace = global)]
extern "C" {
    #[wasm_bindgen(js_name = "eval")]
    fn js_eval_global(code: &str) -> JsValue;
}

/// Evaluate a JavaScript string in the global scope.
fn js_eval(code: &str) -> Result<JsValue, String> {
    let result = js_eval_global(&format!("({})", code));
    Ok(result)
}

/// Read `navigator.gpu` from the global object via js_sys.
///
/// The WebGPU polyfill is loaded via NODE_OPTIONS --require in CI,
/// so js_sys::global() captures the polyfilled state at WASM init time.
fn get_gpu() -> Result<JsValue, String> {
    let global_obj = js_sys::global();
    let navigator = js_sys::Reflect::get(&global_obj, &JsValue::from_str("navigator"))
        .map_err(|e| format!("Failed to get navigator: {:?}", e))?;
    let gpu = js_sys::Reflect::get(&navigator, &JsValue::from_str("gpu"))
        .map_err(|_| "navigator.gpu is not set (WebGPU polyfill may not be active)".to_string())?;
    if gpu.is_undefined() || gpu.is_null() {
        Err("navigator.gpu is undefined/null (WebGPU polyfill may not be active)".to_string())
    } else {
        Ok(gpu)
    }
}

/// Call the WebGPU extract function. Returns a `Vec<u8>` of RGB values.
pub async fn extract_palette_webgpu(
    pixels: &[u8],
    width: u32,
    height: u32,
    color_count: u8,
    quality: u8,
) -> Result<Vec<u8>, String> {
    let expected_size = (width * height * 4) as usize;
    if pixels.len() < expected_size {
        return Err(format!(
            "Buffer too small: expected {} bytes for {}x{} RGBA image, got {}",
            expected_size, width, height, pixels.len()
        ));
    }

    // Read GPU via getter function (bypasses js_sys cached global)
    let gpu = get_gpu()
        .map_err(|e| format!("WebGPU setup error: {}", e))?;

    let extract_fn = js_eval(JS_HELPER)?;

    // Build input object
    let input = js_sys::Object::new();
    let pixels_arr = js_sys::Uint8Array::from(pixels);
    js_sys::Reflect::set(&input, &JsValue::from_str("pixels"), &pixels_arr.into()).ok();
    js_sys::Reflect::set(
        &input,
        &JsValue::from_str("w"),
        &JsValue::from_f64(width as f64),
    )
    .ok();
    js_sys::Reflect::set(
        &input,
        &JsValue::from_str("h"),
        &JsValue::from_f64(height as f64),
    )
    .ok();
    js_sys::Reflect::set(
        &input,
        &JsValue::from_str("maxC"),
        &JsValue::from_f64(color_count as f64),
    )
    .ok();
    js_sys::Reflect::set(
        &input,
        &JsValue::from_str("quality"),
        &JsValue::from_f64(quality as f64),
    )
    .ok();

    // Call the JS helper with gpu as first argument, input as second
    let call_args = js_sys::Array::new();
    call_args.push(&gpu);
    call_args.push(&input.into());
    let fn_ref = extract_fn.unchecked_ref::<js_sys::Function>();
    let promise_val = js_sys::Reflect::apply(fn_ref, &JsValue::UNDEFINED, &call_args)
        .map_err(|e| format!("WebGPU call failed: {:?}", e))?;

    // Convert JsValue to Promise for JsFuture
    let promise = js_sys::Promise::from(promise_val);
    let result = wasm_bindgen_futures::JsFuture::from(promise)
        .await
        .map_err(|e| format!("WebGPU promise rejected: {:?}", e))?;

    let uint8 = js_sys::Uint8Array::from(result);
    let mut out = vec![0u8; uint8.length() as usize];
    uint8.copy_to(&mut out);
    Ok(out)
}
