from typing import List, Tuple, Union

def extract_palette(image: Union[str, bytes], size: int = ..., quality: int = ...) -> List[Tuple[int, int, int]]: ...
def extract_palette_from_buffer(pixels: bytes, width: int, height: int, size: int = ..., quality: int = ...) -> List[Tuple[int, int, int]]: ...
def extract_dominant_color(image: Union[str, bytes], quality: int = ...) -> Tuple[int, int, int]: ...
def extract_dominant_color_from_buffer(pixels: bytes, width: int, height: int, quality: int = ...) -> Tuple[int, int, int]: ...
def list_gpus() -> List[dict]: ...
