# frozen_string_literal: true

require "rb_sys/extensiontask"

GEMSPEC = Gem::Specification.load("modern_colorthief.gemspec")

RbSys::ExtensionTask.new("modern_colorthief", GEMSPEC)

# Tasks expected by oxidize-rb cross-gem action
%w[x86_64-linux aarch64-linux x86_64-darwin arm64-darwin x64-mingw-ucrt].each do |platform|
  Rake::Task.define_task("native:#{platform}") do
    sh "bundle", "exec", "rb-sys-dock", "--platform", platform, "--build"
  end
end
