name: Build and test android APK

on:
    pull_request:
    push:
        branches:
            - main
jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
                os:
                    - 'ubuntu-latest'

        runs-on: ${{ matrix.os }}
        steps:
            - name: Setup python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - uses: actions/checkout@v4
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true
            - name: Install python dependencies
              run: |
                  poetry install --sync --no-interaction --no-root --with test

            - name: Test
              run: |
                  poetry run pytest .
